# Generated by Django 3.2.25 on 2025-05-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadAnomalyDataReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.BigIntegerField()),
                ('acc_x', models.FloatField()),
                ('acc_y', models.FloatField()),
                ('acc_z', models.FloatField()),
                ('rot_x', models.FloatField()),
                ('rot_y', models.FloatField()),
                ('rot_z', models.FloatField()),
                ('speed', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('log_interval', models.DurationField()),
            ],
        ),
    ]
