# Generated by Django 3.2.25 on 2025-05-05 13:50

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadAnomalyDataReceived', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadanomalydatareceived',
            name='log_interval',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='roadanomalydatareceived',
            name='timestamp',
            field=models.TextField(verbose_name=builtins.format),
        ),
    ]
